COMMENT              ::= ^//[^\n]*
COMMENT              ::= ^/\*([^*]|\*[^/])*\*/
WHITESPACE           ::= ^\s+
NONTERMINAL          ::= ^<[^>]*>
COLON_EQ             ::= ^::=
OPENBRACKET          ::= ^\(
CLOSEBRACKET         ::= ^\)
MODIFIER             ::= ^[?+*]
PIPE                 ::= ^\|
END_OF_PRODUCTION    ::= ^;
LITERAL              ::= ^[A-Z_]+(\("([^"\\]|\\.)*"\))?
