<syntaxtree>     ::= <rule>+ ;

<rule>           ::= NONTERMINAL COLON_EQ <production> END_OF_PRODUCTION ;

<production>     ::= <part> (PIPE <part>)* ;

<part>           ::= <element> <cardinality>? ;

<element>        ::= <symbol> | <group> ;

<symbol>         ::= NONTERMINAL | TERMINAL ;

<group>          ::= OPENBRACKET <production> CLOSEBRACKET ;

<cardinality>       ::= MODIFIER("+") | MODIFIER("?") | MODIFIER("*") ;
