<syntax_tree>    ::= <rule>+ ;

<rule>           ::= NONTERMINAL COLON_EQ <production> END_OF_PRODUCTION ;

<production>     ::= <part> (PIPE <part>)* ;

<part>           ::= <element>* ;

<element>        ::= <group> MODIFIER? | <symbol> | <literal>  ;

<symbol>         ::= NONTERMINAL MODIFIER? ;

<literal>        ::= LITERAL MODIFIER? ;

<group>          ::= OPENBRACKET <production> CLOSEBRACKET ;
