; Disasembly of 15PUZZLE
; Generated by chidisas8
;

	.ORG 0x200

		CLS  
		LD   VC, 0x00
		SNE  VC, 0x00
		LD   VE, 0x0F
		LD   I, DATA0
		LD   V0, 0x20
		LD   [I], V0 - V0
		CLS  
LABEL0:
		CALL FUNC6
		CALL FUNC3
		CALL FUNC4
		CALL FUNC2
		CALL FUNC1
		JP   LABEL0
FUNC0:
		LD   V1, 0x00
		LD   V2, 0x17
		LD   V3, 0x04
LABEL1:
		SNE  V1, 0x10
		RET  
		LD   I, DATA1
		ADD  I, V1
		LD   V0 - V0, [I]
		SNE  V0, 0x00
		JP   LABEL2
		LD   I, &CHR[V0]
		DRW  V2, V3, 5
LABEL2:
		ADD  V1, 0x01
		ADD  V2, 0x05
		LD   V4, 0x03
		AND  V4, V1
		SE   V4, 0x00
		JP   LABEL1
		LD   V2, 0x17
		ADD  V3, 0x06
		JP   LABEL1
FUNC1:
		LD   V4, 0x03
		AND  V4, VE
		LD   V5, 0x03
		AND  V5, VD
		SNE  V4, V5
		RET  
		SNE  V4, 0x03
		RET  
		LD   V4, 0x01
		ADD  V4, VE
		CALL FUNC5
		JP   FUNC1
FUNC2:
		LD   V4, 0x03
		AND  V4, VE
		LD   V5, 0x03
		AND  V5, VD
		SNE  V4, V5
		RET  
		SNE  V4, 0x00
		RET  
		LD   V4, 0xFF
		ADD  V4, VE
		CALL FUNC5
		JP   FUNC2
FUNC3:
		LD   V4, 0x0C
		AND  V4, VE
		LD   V5, 0x0C
		AND  V5, VD
		SNE  V4, V5
		RET  
		SNE  V4, 0x00
		RET  
		LD   V4, 0xFC
		ADD  V4, VE
		CALL FUNC5
		JP   FUNC3
FUNC4:
		LD   V4, 0x0C
		AND  V4, VE
		LD   V5, 0x0C
		AND  V5, VD
		SNE  V4, V5
		RET  
		SNE  V4, 0x0C
		RET  
		LD   V4, 0x04
		ADD  V4, VE
		CALL FUNC5
		JP   FUNC4
FUNC5:
		LD   I, DATA1
		ADD  I, V4
		LD   V0 - V0, [I]
		LD   I, DATA1
		ADD  I, VE
		LD   [I], V0 - V0
		LD   V0, 0x00
		LD   I, DATA1
		ADD  I, V4
		LD   [I], V0 - V0
		LD   VE, V4
		RET  
FUNC6:
		SE   VC, 0x00
		JP   LABEL7
		CALL FUNC0
		CALL FUNC7
		CALL FUNC0
		LD   I, DATA2
		ADD  I, VD
		LD   V0 - V0, [I]
		LD   VD, V0
		RET  
LABEL7:
		ADD  VC, 0xFF
		RND  VD, 0x0F
		RET  
FUNC7:
		ADD  VD, 0x01
		LD   V0, 0x0F
		AND  VD, V0
		SKP  VD
		JP   FUNC7
LABEL9:
		SKNP VD
		JP   LABEL9
		RET  
DATA1:
		.DB  0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x09 0x0A 0x0B 0x0C 0x0D 0x0E 0x0F 0x00  ; ................
DATA2:
		.DB  0x0D 0x00 0x01 0x02 0x04 0x05 0x06 0x08 0x09 0x0A 0x0C 0x0E 0x03 0x07 0x0B 0x0F  ; ................
