; Disasembly of BRIX
; Generated by chidisas8
;

	.ORG 0x200

		LD   VE, 0x05
		LD   V5, 0x00
		LD   VB, 0x06
LABEL0:
		LD   VA, 0x00
LABEL1:
		LD   I, DATA0
		DRW  VA, VB, 1
		ADD  VA, 0x04
		SE   VA, 0x40
		JP   LABEL1
		ADD  VB, 0x02
		SE   VB, 0x12
		JP   LABEL0
		LD   VC, 0x20
		LD   VD, 0x1F
		LD   I, DATA2
		DRW  VC, VD, 1
		CALL FUNC0
		LD   V0, 0x00
		LD   V1, 0x00
		LD   I, DATA3
		DRW  V0, V1, 1
		ADD  V0, 0x08
		LD   I, DATA1
		DRW  V0, V1, 1
LABEL2:
		LD   V0, 0x40
		LD   DT, V0
LABEL3:
		LD   V0, DT
		SE   V0, 0x00
		JP   LABEL3
		RND  V6, 0x0F
		LD   V7, 0x1E
		LD   V8, 0x01
		LD   V9, 0xFF
		LD   I, DATA1
		DRW  V6, V7, 1
LABEL4:
		LD   I, DATA2
		DRW  VC, VD, 1
		LD   V0, 0x04
		SKNP V0
		ADD  VC, 0xFE
		LD   V0, 0x06
		SKNP V0
		ADD  VC, 0x02
		LD   V0, 0x3F
		AND  VC, V0
		DRW  VC, VD, 1
		LD   I, DATA1
		DRW  V6, V7, 1
		ADD  V6, V8
		ADD  V7, V9
		LD   V0, 0x3F
		AND  V6, V0
		LD   V1, 0x1F
		AND  V7, V1
		SNE  V7, 0x1F
		JP   LABEL7
LABEL5:
		SNE  V6, 0x00
		LD   V8, 0x01
		SNE  V6, 0x3F
		LD   V8, 0xFF
		SNE  V7, 0x00
		LD   V9, 0x01
		DRW  V6, V7, 1
		SE   VF, 0x01
		JP   LABEL6
		SNE  V7, 0x1F
		JP   LABEL6
		LD   V0, 0x05
		SUB  V0, V7
		SE   VF, 0x00
		JP   LABEL6
		LD   V0, 0x01
		LD   ST, V0
		LD   V0, V6
		LD   V1, 0xFC
		AND  V0, V1
		LD   I, DATA0
		DRW  V0, V7, 1
		LD   V0, 0xFE
		XOR  V9, V0
		CALL FUNC0
		ADD  V5, 0x01
		CALL FUNC0
		SNE  V5, 0x60
		JP   LABEL9
LABEL6:
		JP   LABEL4
LABEL7:
		LD   V9, 0xFF
		LD   V0, V6
		SUB  V0, VC
		SE   VF, 0x01
		JP   LABEL8
		LD   V1, 0x02
		SUB  V0, V1
		SE   VF, 0x01
		JP   LABEL10
		SUB  V0, V1
		SE   VF, 0x01
		JP   LABEL12
		SUB  V0, V1
		SE   VF, 0x01
		JP   LABEL11
LABEL8:
		LD   V0, 0x20
		LD   ST, V0
		LD   I, DATA1
		ADD  VE, 0xFF
		LD   V0, VE
		ADD  V0, V0
		LD   V1, 0x00
		DRW  V0, V1, 1
		SE   VE, 0x00
		JP   LABEL2
LABEL9:
		JP   LABEL9
LABEL10:
		ADD  V8, 0xFF
		SNE  V8, 0xFE
		LD   V8, 0xFF
		JP   LABEL12
LABEL11:
		ADD  V8, 0x01
		SNE  V8, 0x02
		LD   V8, 0x01
LABEL12:
		LD   V0, 0x04
		LD   ST, V0
		LD   V9, 0xFF
		JP   LABEL5
FUNC0:
		LD   I, DATA4
		LD   [I], BCD[V5]
		LD   V0 - V2, [I]
		LD   I, &CHR[V1]
		LD   V3, 0x37
		LD   V4, 0x00
		DRW  V3, V4, 5
		ADD  V3, 0x05
		LD   I, &CHR[V2]
		DRW  V3, V4, 5
		RET  
DATA0:
		.DB  0xE0 0x00  ; ..
DATA1:
		.DB  0x80 0x00  ; ..
DATA2:
		.DB  0xFC 0x00  ; ..
DATA3:
		.DB  0xAA 0x00  ; ..
DATA4:
		.DB  0x00 0x00 0x00 0x00  ; ....
