; Disasembly of KALEID
; Generated by chidisas8
;

	.ORG 0x200

DATA0:
		LD   V0, 0x00
		LD   V3, 0x80
		LD   V1, 0x1F
		LD   V2, 0x0F
LABEL0:
		CALL FUNC0
		LD   I, DATA0
		ADD  I, V3
		LD   V0, K
		LD   [I], V0 - V0
		SNE  V0, 0x00
		JP   LABEL1
		ADD  V3, 0x01
		SE   V3, 0x00
		JP   LABEL0
LABEL1:
		LD   V3, 0x80
LABEL2:
		LD   I, DATA0
		ADD  I, V3
		LD   V0 - V0, [I]
		SNE  V0, 0x00
		JP   LABEL1
		ADD  V3, 0x01
		SNE  V3, 0x00
		JP   LABEL1
		CALL FUNC0
		JP   LABEL2
FUNC0:
		SNE  V0, 0x02
		ADD  V2, 0xFF
		SNE  V0, 0x04
		ADD  V1, 0xFF
		SNE  V0, 0x06
		ADD  V1, 0x01
		SNE  V0, 0x08
		ADD  V2, 0x01
		LD   I, DATA1
		LD   VA, 0xE0
		AND  VA, V1
		LD   VB, 0x1F
		AND  V1, VB
		SE   VA, 0x00
		ADD  V2, 0x01
		LD   VA, 0xF0
		AND  VA, V2
		LD   VB, 0x0F
		AND  V2, VB
		SE   VA, 0x00
		ADD  V1, 0x01
		LD   VB, 0x1F
		AND  V1, VB
		DRW  V1, V2, 1
		LD   VA, V1
		LD   VB, 0x1F
		SUB  VB, V2
		DRW  VA, VB, 1
		LD   VA, 0x3F
		SUB  VA, V1
		DRW  VA, VB, 1
		LD   VB, V2
		DRW  VA, VB, 1
		RET  
		.DB  0x01  ; .
DATA1:
		.DB  0x80  ; .
