; Disasembly of MAZE
; Generated by chidisas8
;

	.ORG 0x200

		LD   V0, 0x00
		LD   V1, 0x00
LABEL0:
		LD   I, DATA1
		RND  V2, 0x01
		SE   V2, 0x01
		LD   I, DATA0
		DRW  V0, V1, 4
		ADD  V0, 0x04
		SE   V0, 0x40
		JP   LABEL0
		LD   V0, 0x00
		ADD  V1, 0x04
		SE   V1, 0x20
		JP   LABEL0
LABEL1:
		JP   LABEL1
DATA0:
		.DB  0x80 0x40 0x20 0x10  ; .@ .
DATA1:
		.DB  0x20 0x40 0x80 0x10  ;  @..
