; Disasembly of PONG2
; Generated by chidisas8
;

	.ORG 0x200

		CALL FUNC1
		LD   VB, 0x0C
		LD   VC, 0x3F
		LD   VD, 0x0C
		LD   I, DATA0
		DRW  VA, VB, 6
		DRW  VC, VD, 6
		LD   VE, 0x00
		CALL FUNC0
		LD   V6, 0x03
		LD   V8, 0x02
LABEL0:
		LD   V0, 0x60
		LD   DT, V0
LABEL1:
		LD   V0, DT
		SE   V0, 0x00
		JP   LABEL1
		RND  V7, 0x17
		ADD  V7, 0x08
		LD   V9, 0xFF
		LD   I, DATA1
		DRW  V6, V7, 1
LABEL2:
		LD   I, DATA0
		DRW  VA, VB, 6
		DRW  VC, VD, 6
		LD   V0, 0x01
		SKNP V0
		ADD  VB, 0xFE
		LD   V0, 0x04
		SKNP V0
		ADD  VB, 0x02
		LD   V0, 0x1F
		AND  VB, V0
		DRW  VA, VB, 6
		LD   V0, 0x0C
		SKNP V0
		ADD  VD, 0xFE
		LD   V0, 0x0D
		SKNP V0
		ADD  VD, 0x02
		LD   V0, 0x1F
		AND  VD, V0
		DRW  VC, VD, 6
		LD   I, DATA1
		DRW  V6, V7, 1
		ADD  V6, V8
		ADD  V7, V9
		LD   V0, 0x3F
		AND  V6, V0
		LD   V1, 0x1F
		AND  V7, V1
		SNE  V6, 0x00
		JP   LABEL4
		SNE  V6, 0x3F
		JP   LABEL5
LABEL3:
		SNE  V7, 0x1F
		LD   V9, 0xFF
		SNE  V7, 0x00
		LD   V9, 0x01
		DRW  V6, V7, 1
		JP   LABEL2
LABEL4:
		LD   V8, 0x02
		LD   V3, 0x01
		LD   V0, V7
		SUB  V0, VB
		JP   LABEL6
LABEL5:
		LD   V8, 0xFE
		LD   V3, 0x0A
		LD   V0, V7
		SUB  V0, VD
LABEL6:
		SE   VF, 0x01
		JP   LABEL7
		LD   V1, 0x02
		SUB  V0, V1
		SE   VF, 0x01
		JP   LABEL8
		SUB  V0, V1
		SE   VF, 0x01
		JP   LABEL10
		SUB  V0, V1
		SE   VF, 0x01
		JP   LABEL9
LABEL7:
		LD   V0, 0x20
		LD   ST, V0
		CALL FUNC0
		ADD  VE, V3
		CALL FUNC0
		LD   V6, 0x3E
		SE   V3, 0x01
		LD   V6, 0x03
		LD   V8, 0xFE
		SE   V3, 0x01
		LD   V8, 0x02
		JP   LABEL0
LABEL8:
		ADD  V9, 0xFF
		SNE  V9, 0xFE
		LD   V9, 0xFF
		JP   LABEL10
LABEL9:
		ADD  V9, 0x01
		SNE  V9, 0x02
		LD   V9, 0x01
LABEL10:
		LD   V0, 0x04
		LD   ST, V0
		ADD  V6, 0x01
		SNE  V6, 0x40
		ADD  V6, 0xFE
		JP   LABEL3
FUNC0:
		LD   I, DATA2
		LD   [I], BCD[VE]
		LD   V0 - V2, [I]
		LD   I, &CHR[V1]
		LD   V4, 0x14
		LD   V5, 0x02
		DRW  V4, V5, 5
		ADD  V4, 0x15
		LD   I, &CHR[V2]
		DRW  V4, V5, 5
		RET  
DATA0:
		.DB  0x80 0x80 0x80 0x80 0x80 0x80  ; ......
DATA1:
		.DB  0x80 0x00  ; ..
DATA2:
		.DB  0x00 0x00 0x00 0x00  ; ....
DATA3:
		.DB  0xC0 0xC0 0xC0 0x00  ; ....
DATA4:
		.DB  0xFF 0x00  ; ..
FUNC1:
		LD   VB, 0x20
		LD   VC, 0x00
		LD   I, DATA3
LABEL11:
		DRW  VB, VC, 4
		ADD  VC, 0x04
		SE   VC, 0x20
		JP   LABEL11
		LD   VA, 0x00
		LD   VB, 0x00
		LD   VC, 0x1F
		LD   I, DATA4
LABEL12:
		DRW  VA, VB, 1
		DRW  VA, VC, 1
		ADD  VA, 0x08
		SE   VA, 0x40
		JP   LABEL12
		LD   I, DATA3
		LD   VA, 0x00
		LD   VB, 0x20
		DRW  VB, VA, 1
		RET  
