; Disasembly of PUZZLE
; Generated by chidisas8
;

	.ORG 0x200

		LD   VA, 0x12
		LD   VB, 0x01
		LD   V1, 0x10
		LD   V2, 0x00
		LD   V0, 0x00
LABEL0:
		LD   I, DATA0
		DRW  V1, V2, 7
		LD   I, &CHR[V0]
		SE   V0, 0x00
		DRW  VA, VB, 5
		ADD  V1, 0x08
		ADD  VA, 0x08
		SE   V1, 0x30
		JP   LABEL1
		LD   V1, 0x10
		ADD  V2, 0x08
		LD   VA, 0x12
		ADD  VB, 0x08
LABEL1:
		LD   I, DATA1
		ADD  I, V0
		LD   [I], V0 - V0
		ADD  V0, 0x01
		SE   V0, 0x10
		JP   LABEL0
		LD   VA, 0x12
		LD   VB, 0x01
		LD   VC, 0x00
		LD   V2, 0xFF
LABEL2:
		RND  V0, 0x06
		ADD  V0, 0x02
		CALL FUNC0
		ADD  V2, 0xFF
		SE   V2, 0x00
		JP   LABEL2
		LD   VE, 0x00
		LD   VE, 0x00
LABEL3:
		LD   V0, K
		CALL FUNC0
		ADD  VE, 0x01
		ADD  VE, 0x01
		JP   LABEL3
FUNC0:
		LD   V4, VA
		LD   V5, VB
		LD   V6, VC
		SE   V0, 0x02
		JP   LABEL4
		SNE  V5, 0x01
		JP   LABEL4
		ADD  V5, 0xF8
		ADD  V6, 0xFC
LABEL4:
		SE   V0, 0x08
		JP   LABEL5
		SNE  V5, 0x19
		JP   LABEL5
		ADD  V5, 0x08
		ADD  V6, 0x04
LABEL5:
		SE   V0, 0x06
		JP   LABEL6
		SNE  V4, 0x12
		JP   LABEL6
		ADD  V4, 0xF8
		ADD  V6, 0xFF
LABEL6:
		SE   V0, 0x04
		JP   LABEL7
		SNE  V4, 0x2A
		JP   LABEL7
		ADD  V4, 0x08
		ADD  V6, 0x01
LABEL7:
		LD   I, DATA1
		ADD  I, V6
		LD   V0 - V0, [I]
		LD   V1, V0
		LD   V0, 0x00
		LD   I, DATA1
		ADD  I, V6
		LD   [I], V0 - V0
		LD   I, DATA1
		ADD  I, VC
		LD   V0, V1
		LD   [I], V0 - V0
		LD   I, &CHR[V1]
		DRW  V4, V5, 5
		DRW  VA, VB, 5
		LD   VA, V4
		LD   VB, V5
		LD   VC, V6
		RET  
		.DB  0xEE 0x5E  ; .^
DATA0:
		.DB  0xFE 0xFE 0xFE 0xFE 0xFE 0xFE 0xFE 0xFE  ; ........
