; Disasembly of SQUASH
; Generated by chidisas8
;

	.ORG 0x200

		LD   I, DATA2
		LD   V0, 0x00
		LD   V1, 0x00
		LD   V2, 0x1E
LABEL0:
		DRW  V0, V1, 1
		DRW  V0, V2, 1
		ADD  V0, 0x08
		SE   V0, 0x40
		JP   LABEL0
		LD   I, DATA1
		LD   V0, 0x3E
		LD   V1, 0x01
LABEL1:
		DRW  V0, V1, 5
		ADD  V1, 0x05
		SE   V1, 0x1A
		JP   LABEL1
		DRW  V0, V1, 4
		LD   V3, 0x00
		RND  V4, 0x0F
		ADD  V4, 0x08
		LD   V5, 0x01
		OR   V4, V5
		LD   V5, 0x03
		LD   V6, 0x02
		LD   V7, 0x01
		LD   V8, V4
		ADD  V8, 0x02
		LD   V9, 0x01
		LD   VA, 0x04
		LD   VB, 0x05
		CALL FUNC1
		LD   I, DATA0
		DRW  V3, V4, 5
		DRW  V7, V8, 1
LABEL2:
		LD   VC, 0x01
		CALL FUNC0
		LD   I, DATA0
		LD   VC, V7
		LD   VD, V8
		SKP  V9
		JP   LABEL3
		SNE  V4, 0x01
		JP   LABEL3
		DRW  V3, V4, 5
		ADD  V4, 0xFF
		DRW  V3, V4, 5
LABEL3:
		SKP  VA
		JP   LABEL4
		SNE  V4, 0x19
		JP   LABEL4
		DRW  V3, V4, 5
		ADD  V4, 0x01
		DRW  V3, V4, 5
LABEL4:
		ADD  V7, V5
		ADD  V8, V6
		SNE  V7, 0x01
		LD   V5, 0x03
		SNE  V7, 0x3D
		LD   V5, 0xFD
		SNE  V8, 0x01
		LD   V6, 0x02
		SNE  V8, 0x1D
		LD   V6, 0xFE
		DRW  VC, VD, 1
		DRW  V7, V8, 1
		SE   V7, 0x01
		JP   LABEL2
		LD   VC, V8
		SUB  VC, V4
		LD   VD, 0x00
LABEL5:
		SNE  VC, VD
		JP   LABEL2
		ADD  VD, 0x01
		SE   VD, 0x05
		JP   LABEL5
		LD   VC, K
		CALL FUNC1
		ADD  VB, 0xFF
		CALL FUNC1
		SE   VB, 0xFF
		JP   LABEL2
		CALL FUNC1
		LD   VB, 0x00
LABEL6:
		CALL FUNC1
		LD   VC, 0x1E
		CALL FUNC0
		JP   LABEL6
FUNC0:
		LD   DT, VC
LABEL7:
		LD   VC, DT
		SE   VC, 0x00
		JP   LABEL7
		RET  
FUNC1:
		LD   I, DATA3
		LD   [I], BCD[VB]
		LD   V0 - V2, [I]
		LD   I, &CHR[V2]
		LD   V0, 0x39
		LD   V1, 0x02
		DRW  V0, V1, 5
		RET  
DATA0:
		.DB  0x80 0x80 0x80 0x80 0x80  ; .....
DATA1:
		.DB  0xE0 0xE0 0xE0 0xE0 0xE0  ; .....
DATA2:
		.DB  0xFF  ; .
