; Disasembly of SYZYGY
; Generated by chidisas8
;

	.ORG 0x200

		JP   LABEL0
		.DB  0x8D 0x8D 0x20 0xA9 0x31 0x39 0x39 0x30 0x20 0x52 0x54 0x54 0x20 0x8E 0x8E 0x00  ; .. .1990 RTT ...
LABEL0:
		CALL FUNC1
		CALL FUNC2
LABEL1:
		LD   V0, 0x0F
		SKNP V0
		JP   LABEL2
		LD   V0, 0x0E
		SKNP V0
		JP   LABEL3
		JP   LABEL1
LABEL2:
		CALL FUNC2
		JP   LABEL4
LABEL3:
		CLS  
		JP   LABEL4
LABEL4:
		RND  V1, 0x1F
		ADD  V1, 0x10
		RND  V2, 0x0F
		ADD  V2, 0x08
		RND  V3, 0x03
		LD   V5, V3
		LD   V6, V1
		LD   V7, V2
		LD   V8, V3
		SNE  V8, 0x00
		ADD  V7, 0x01
		SNE  V8, 0x01
		ADD  V7, 0xFF
		SNE  V8, 0x02
		ADD  V6, 0x01
		SNE  V8, 0x03
		ADD  V6, 0xFF
		LD   I, DATA0
		DRW  V1, V2, 1
		DRW  V6, V7, 1
		LD   V4, 0xF0
		LD   V9, 0xF1
		LD   I, DATA16
		ADD  I, V4
		LD   V0, V3
		LD   [I], V0 - V0
		ADD  V4, 0x01
		LD   I, DATA16
		ADD  I, V4
		LD   V0, 0x01
		LD   [I], V0 - V0
		CALL FUNC3
		LD   VA, 0x00
		ADD  VA, 0x00
LABEL5:
		LD   V0, DT
		SE   V0, 0x00
		JP   LABEL8
		SE   VD, 0x00
		JP   LABEL7
		LD   V0, 0x00
		LD   I, &CHR[V0]
		DRW  VB, VC, 5
		SE   VF, 0x01
		JP   LABEL6
		DRW  VB, VC, 5
		CALL FUNC3
		LD   DT, V0
		JP   LABEL8
LABEL6:
		LD   DT, VE
		LD   VD, 0x01
		LD   VE, 0x00
		JP   LABEL8
LABEL7:
		LD   V0, VE
		LD   I, &CHR[V0]
		DRW  VB, VC, 5
		CALL FUNC3
LABEL8:
		LD   V0, 0x03
		SKNP V0
		LD   V3, 0x00
		LD   V0, 0x06
		SKNP V0
		LD   V3, 0x01
		LD   V0, 0x07
		SKNP V0
		LD   V3, 0x02
		LD   V0, 0x08
		SKNP V0
		LD   V3, 0x03
		SNE  V3, 0x00
		ADD  V2, 0xFF
		SNE  V3, 0x01
		ADD  V2, 0x01
		SNE  V3, 0x02
		ADD  V1, 0xFF
		SNE  V3, 0x03
		ADD  V1, 0x01
		LD   I, DATA0
		DRW  V1, V2, 1
		SE   VF, 0x01
		JP   LABEL10
		SE   VD, 0x01
		JP   LABEL14
		LD   V0, 0x3F
		AND  V1, V0
		LD   V0, 0x1F
		AND  V2, V0
		LD   V0, VB
		SUBN V0, V1
		SE   VF, 0x01
		JP   LABEL14
		LD   V0, VB
		ADD  V0, 0x03
		SUB  V0, V1
		SE   VF, 0x01
		JP   LABEL14
		LD   V0, VC
		SUBN V0, V2
		SE   VF, 0x01
		JP   LABEL14
		LD   V0, VC
		ADD  V0, 0x04
		SUB  V0, V2
		SE   VF, 0x01
		JP   LABEL14
		LD   V0, 0x04
		LD   ST, V0
		RND  VE, 0x07
		ADD  VE, 0x02
		ADD  VA, VE
		LD   I, DATA0
		DRW  V1, V2, 1
		LD   V0, 0x00
		LD   I, &CHR[V0]
		DRW  VB, VC, 5
		LD   V0, VE
		LD   I, &CHR[V0]
		DRW  VB, VC, 5
		LD   V0, 0x30
		LD   DT, V0
LABEL9:
		LD   V0, DT
		SE   V0, 0x00
		JP   LABEL9
		LD   I, DATA0
		DRW  V1, V2, 1
LABEL10:
		SNE  V3, V5
		JP   LABEL11
		ADD  V4, 0x01
		LD   I, DATA16
		ADD  I, V4
		LD   V0, V3
		LD   [I], V0 - V0
		ADD  V4, 0x01
		LD   I, DATA16
		ADD  I, V4
		LD   V0, 0x00
		LD   [I], V0 - V0
		LD   V5, V3
LABEL11:
		LD   I, DATA16
		ADD  I, V4
		LD   V0 - V0, [I]
		ADD  V0, 0x01
		LD   [I], V0 - V0
		SNE  VA, 0x00
		JP   LABEL13
		LD   V0, 0x0C
LABEL12:
		ADD  V0, 0xFF
		SE   V0, 0x00
		JP   LABEL12
		ADD  VA, 0xFF
		JP   LABEL5
LABEL13:
		LD   I, DATA0
		DRW  V6, V7, 1
		SNE  V8, 0x00
		ADD  V7, 0xFF
		SNE  V8, 0x01
		ADD  V7, 0x01
		SNE  V8, 0x02
		ADD  V6, 0xFF
		SNE  V8, 0x03
		ADD  V6, 0x01
		LD   I, DATA16
		ADD  I, V9
		LD   V0 - V0, [I]
		ADD  V0, 0xFF
		LD   [I], V0 - V0
		SE   V0, 0x00
		JP   LABEL5
		ADD  V9, 0x01
		LD   I, DATA16
		ADD  I, V9
		LD   V0 - V0, [I]
		LD   V8, V0
		ADD  V9, 0x01
		JP   LABEL5
LABEL14:
		LD   V0, 0x0D
		LD   ST, V0
		LD   V0, 0x0B
LABEL15:
		SKP  V0
		JP   LABEL15
		LD   VB, 0x01
		LD   VC, 0x00
		LD   VD, 0x00
LABEL16:
		ADD  VB, 0x01
		SE   VB, 0x0A
		JP   LABEL17
		LD   VB, 0x00
		ADD  VC, 0x01
		SE   VC, 0x0A
		JP   LABEL17
		LD   VC, 0x00
		ADD  VD, 0x01
LABEL17:
		LD   I, DATA0
		DRW  V6, V7, 1
		SNE  V8, 0x00
		ADD  V7, 0xFF
		SNE  V8, 0x01
		ADD  V7, 0x01
		SNE  V8, 0x02
		ADD  V6, 0xFF
		SNE  V8, 0x03
		ADD  V6, 0x01
		LD   I, DATA16
		ADD  I, V9
		LD   V0 - V0, [I]
		ADD  V0, 0xFF
		LD   [I], V0 - V0
		SE   V0, 0x00
		JP   LABEL16
		SNE  V9, V4
		JP   LABEL18
		ADD  V9, 0x01
		LD   I, DATA16
		ADD  I, V9
		LD   V0 - V0, [I]
		LD   V8, V0
		ADD  V9, 0x01
		JP   LABEL16
LABEL18:
		CLS  
		LD   V6, 0x11
		LD   V7, 0x09
		LD   V8, 0x2F
		LD   V9, 0x17
		LD   I, DATA3
		DRW  V6, V7, 14
		DRW  V8, V7, 14
		ADD  V7, 0xFF
		LD   I, DATA1
		DRW  V6, V7, 1
		DRW  V6, V9, 1
		ADD  V6, 0x08
		DRW  V6, V7, 1
		DRW  V6, V9, 1
		ADD  V6, 0x08
		DRW  V6, V7, 1
		DRW  V6, V9, 1
		ADD  V6, 0x08
		LD   I, DATA2
		DRW  V6, V7, 1
		DRW  V6, V9, 1
		LD   I, DATA12
		LD   V6, 0x13
		LD   V7, 0x11
		CALL FUNC0
		LD   I, DATA15
		LD   V0 - V3, [I]
		SNE  V3, VD
		JP   LABEL19
		LD   V0, V3
		SUB  V0, VD
		SE   VF, 0x01
		JP   LABEL21
		JP   LABEL22
LABEL19:
		SNE  V2, VC
		JP   LABEL20
		LD   V0, V2
		SUB  V0, VC
		SE   VF, 0x01
		JP   LABEL21
		JP   LABEL22
LABEL20:
		LD   V0, V1
		SUB  V0, VB
		SE   VF, 0x00
		JP   LABEL22
LABEL21:
		LD   I, DATA15
		LD   V3, VD
		LD   V2, VC
		LD   V1, VB
		LD   [I], V0 - V3
LABEL22:
		LD   I, DATA15
		LD   V0 - V3, [I]
		LD   V6, 0x13
		ADD  V7, 0xF9
		LD   VD, V3
		LD   VC, V2
		LD   VB, V1
		LD   I, DATA13
		CALL FUNC0
LABEL23:
		RND  V1, 0x3F
		RND  V2, 0x1F
		LD   V0, 0x0D
		SUB  V0, V1
		SE   VF, 0x00
		JP   LABEL24
		LD   V0, 0x30
		SUBN V0, V1
		SE   VF, 0x00
		JP   LABEL24
		LD   V0, 0x03
		SUB  V0, V2
		SE   VF, 0x00
		JP   LABEL24
		LD   V0, 0x18
		SUBN V0, V2
		SE   VF, 0x00
		JP   LABEL24
		JP   LABEL25
LABEL24:
		RND  V3, 0x0F
		LD   I, &CHR[V3]
		DRW  V1, V2, 5
LABEL25:
		LD   V0, 0x0F
		SKNP V0
		JP   LABEL26
		LD   V0, 0x0E
		SKNP V0
		JP   LABEL27
		JP   LABEL23
LABEL26:
		CLS  
		CALL FUNC1
		JP   LABEL4
LABEL27:
		CLS  
		JP   LABEL4
FUNC0:
		DRW  V6, V7, 5
		LD   I, DATA14
		ADD  V6, 0x02
		DRW  V6, V7, 4
		LD   I, &CHR[VD]
		ADD  V6, 0x0A
		DRW  V6, V7, 5
		LD   I, &CHR[VC]
		ADD  V6, 0x05
		DRW  V6, V7, 5
		LD   I, &CHR[VB]
		ADD  V6, 0x05
		DRW  V6, V7, 5
		RET  
FUNC1:
		LD   I, DATA1
		LD   V1, 0x00
		LD   V2, 0x00
		LD   V6, 0x1F
LABEL28:
		DRW  V1, V2, 1
		DRW  V1, V6, 1
		ADD  V1, 0x08
		SE   V1, 0x40
		JP   LABEL28
		LD   I, DATA3
		LD   V2, 0x01
		LD   V5, 0x3F
		DRW  V1, V2, 15
		DRW  V5, V2, 15
		ADD  V2, 0x0F
		DRW  V1, V2, 15
		DRW  V5, V2, 15
		RET  
FUNC2:
		LD   V1, 0x0C
		LD   V2, 0x07
		LD   I, DATA4
		DRW  V1, V2, 10
		LD   I, DATA5
		ADD  V1, 0x06
		DRW  V1, V2, 10
		LD   I, DATA6
		ADD  V1, 0x06
		DRW  V1, V2, 10
		LD   I, DATA5
		ADD  V1, 0x06
		DRW  V1, V2, 10
		LD   I, DATA7
		ADD  V1, 0x06
		DRW  V1, V2, 10
		LD   I, DATA5
		ADD  V1, 0x06
		DRW  V1, V2, 10
		LD   V1, 0x0E
		LD   V2, 0x18
		LD   I, DATA8
		DRW  V1, V2, 3
		LD   I, DATA9
		ADD  V1, 0x08
		ADD  V2, 0xFF
		DRW  V1, V2, 4
		ADD  V1, 0x09
		ADD  V2, 0xFE
		LD   I, DATA10
		DRW  V1, V2, 6
		ADD  V1, 0x06
		ADD  V2, 0x01
		LD   I, DATA11
		DRW  V1, V2, 5
		RET  
FUNC3:
		LD   VD, 0xC5
LABEL29:
		RND  VB, 0x3F
		LD   VE, VB
		ADD  VE, VD
		SNE  VF, 0x01
		JP   LABEL29
		ADD  VB, 0x01
		LD   VD, 0xE6
LABEL30:
		RND  VC, 0x1F
		LD   VE, VC
		ADD  VE, VD
		SNE  VF, 0x01
		JP   LABEL30
		ADD  VC, 0x01
		LD   VD, 0x00
		RND  VE, 0x3F
		ADD  VE, 0x40
		LD   DT, VE
		RND  VE, 0x3F
		ADD  VE, 0x40
		RET  
DATA0:
		.DB  0x80 0x00  ; ..
DATA1:
		.DB  0xFF 0x00  ; ..
DATA2:
		.DB  0xFE 0x00  ; ..
DATA3:
		.DB  0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80 0x80  ; ................
DATA4:
		.DB  0x1F 0x10 0x10 0x10 0x1F 0x01 0x01 0x01 0x01 0x1F  ; ..........
DATA5:
		.DB  0x11 0x11 0x11 0x11 0x1F 0x04 0x04 0x04 0x04 0x04  ; ..........
DATA6:
		.DB  0x1F 0x01 0x02 0x02 0x04 0x04 0x08 0x08 0x10 0x1F  ; ..........
DATA7:
		.DB  0x1F 0x11 0x10 0x10 0x10 0x13 0x11 0x11 0x11 0x1F  ; ..........
DATA8:
		.DB  0x05 0x05 0x02 0x00  ; ....
DATA9:
		.DB  0x71 0x51 0x51 0x75  ; qQQu
DATA10:
		.DB  0x0C 0x12 0x1E 0x14 0x12 0x09  ; ......
DATA11:
		.DB  0x14 0x3E 0x15 0x15 0x2A 0x00  ; .>..*.
DATA12:
		.DB  0x77 0x44 0x24 0x14 0x77 0x00  ; wD$.w.
DATA13:
		.DB  0x57 0x52 0x72 0x52 0x57 0x00  ; WRrRW.
DATA14:
		.DB  0x00 0x01 0x00 0x01  ; ....
DATA15:
		.DB  0x00 0x00 0x00 0x00  ; ....
