; Disasembly of TANK
; Generated by chidisas8
;

	.ORG 0x200

		JP   LABEL1
LABEL0:
		ADD  V6, 0xFB
		LD   V0, 0x20
		SUB  V0, V6
		SNE  VF, 0x00
		LD   V6, 0x00
		JP   LABEL13
		.DB  0x00 0xFF 0x00 0x00  ; ....
DATA0:
		.DB  0x00 0x01 0x00 0x0C 0x0A  ; .....
DATA1:
		.DB  0x00 0x19  ; ..
DATA2:
		.DB  0x02 0x04 0x06 0x08  ; ....
DATA3:
		.DB  0x02 0x02 0x03 0x2C 0x00 0x0F  ; ...,..
DATA4:
		.DB  0x00 0x02 0x05 0x2E 0x08 0x00  ; ......
DATA5:
		.DB  0x00 0x02 0x05 0x00 0x00 0x00 0x00  ; .......
LABEL1:
		LD   VE, 0x00
		LD   VD, 0xA0
		LD   VA, 0x08
		LD   V9, 0x06
		LD   V8, 0x04
		LD   V7, 0x02
		LD   V6, 0x19
		LD   V4, 0x10
		LD   V3, 0x0C
		LD   V2, 0x00
		LD   V1, 0x06
		LD   I, DATA0
		LD   [I], V0 - VA
LABEL2:
		CALL FUNC10
		LD   V0, 0x40
		LD   DT, V0
LABEL3:
		LD   V0, DT
		SE   V0, 0x00
		JP   LABEL3
		CALL FUNC10
		CALL FUNC4
		CALL FUNC6
		LD   I, DATA0
		LD   V0 - V5, [I]
		CALL FUNC1
LABEL4:
		CALL FUNC2
		CALL FUNC3
		SE   VF, 0x01
		CALL FUNC5
		SE   VF, 0x01
		CALL FUNC3
		SE   VF, 0x01
		CALL FUNC3
		SE   VF, 0x01
		CALL FUNC0
		SNE  VF, 0x01
		JP   LABEL11
		JP   LABEL4
FUNC0:
		LD   I, DATA0
		LD   V0 - V5, [I]
		SNE  V6, 0x00
		SE   V5, 0x00
		JP   LABEL5
		JP   LABEL14
LABEL5:
		SKNP V7
		LD   V2, 0x09
		SKNP V8
		LD   V2, 0x04
		SKNP V9
		LD   V2, 0x06
		SKNP VA
		LD   V2, 0x01
		SNE  V2, 0x00
		RET  
		CALL FUNC1
		LD   V1, V2
		CALL FUNC7
		CALL FUNC8
		LD   VC, 0x01
		LD   V2, 0x00
		LD   VF, 0x00
		LD   I, DATA0
		LD   [I], V0 - V5
FUNC1:
		LD   I, DATA6
		SNE  V1, 0x01
		LD   V0, 0x00
		SNE  V1, 0x04
		LD   V0, 0x13
		SNE  V1, 0x06
		LD   V0, 0x0D
		SNE  V1, 0x09
		LD   V0, 0x06
		ADD  I, V0
		DRW  V3, V4, 7
		RET  
FUNC2:
		LD   V0, 0x05
		SKP  V0
		RET  
		SNE  V5, 0x0F
		RET  
		LD   V5, 0x0F
		ADD  V6, 0xFF
		LD   I, DATA0
		LD   [I], V0 - V5
		ADD  V4, 0x03
		ADD  V3, 0x03
		CALL FUNC7
		CALL FUNC7
		CALL FUNC7
		LD   I, DATA4
		LD   [I], V0 - V5
		LD   I, DATA7
		DRW  V3, V4, 1
		RET  
FUNC3:
		LD   I, DATA4
		LD   V0 - V5, [I]
		SNE  V5, 0x00
		RET  
		LD   I, DATA7
		DRW  V3, V4, 1
		CALL FUNC7
		LD   VC, 0x02
		CALL FUNC9
		SNE  VB, 0xBB
		JP   FUNC4
		DRW  V3, V4, 1
LABEL6:
		LD   I, DATA4
		LD   [I], V0 - V5
		RET  
FUNC4:
		LD   V5, 0x00
		LD   V0, 0x00
		LD   I, DATA1
		LD   [I], V0 - V0
		JP   LABEL6
FUNC5:
		LD   I, DATA3
		LD   V0 - V5, [I]
		SE   V5, 0x0F
		JP   LABEL10
		LD   I, DATA8
		DRW  V3, V4, 5
		SE   V2, 0x00
		JP   LABEL8
		RND  V1, 0x03
		LD   I, DATA2
		ADD  I, V1
		LD   V0 - V0, [I]
		LD   V1, V0
		RND  V2, 0x0F
		ADD  V2, 0x01
LABEL8:
		CALL FUNC7
		LD   I, DATA8
		LD   VC, 0x03
		ADD  V2, 0xFF
		LD   VF, 0x00
		DRW  V3, V4, 5
LABEL9:
		LD   I, DATA3
		LD   [I], V0 - V5
		RET  
LABEL10:
		RND  V4, 0x07
		LD   I, DATA9
		ADD  I, V4
		LD   V0 - V0, [I]
		LD   V3, V0
		LD   I, DATA10
		ADD  I, V4
		LD   V0 - V0, [I]
		LD   V4, V0
		LD   I, DATA8
		DRW  V3, V4, 5
		LD   V0, 0x20
		LD   ST, V0
		LD   V5, 0x0F
		JP   LABEL9
FUNC6:
		LD   V5, 0x00
		JP   LABEL9
LABEL11:
		SNE  VC, 0x01
		JP   LABEL0
		SNE  VC, 0x02
		JP   LABEL12
		LD   I, DATA4
		LD   V0 - V5, [I]
		SNE  V5, 0x00
		JP   LABEL0
		LD   I, DATA7
		DRW  V3, V4, 1
		LD   VF, 0x00
		DRW  V3, V4, 1
		SE   VF, 0x01
		JP   LABEL0
LABEL12:
		ADD  VE, 0x0A
LABEL13:
		LD   V0, 0x40
		LD   ST, V0
		CLS  
		JP   LABEL2
LABEL14:
		CLS  
		CALL FUNC10
		LD   V0, 0x60
		LD   ST, V0
LABEL15:
		JP   LABEL15
		.DB  0x6E 0x00 0x13 0x84  ; n...
FUNC7:
		SNE  V1, 0x01
		ADD  V4, 0xFF
		SNE  V1, 0x04
		ADD  V3, 0xFF
		SNE  V1, 0x06
		ADD  V3, 0x01
		SNE  V1, 0x09
		ADD  V4, 0x01
		RET  
FUNC8:
		SNE  V4, 0x00
		ADD  V4, 0x01
		SNE  V3, 0x00
		ADD  V3, 0x01
		SNE  V3, 0x38
		ADD  V3, 0xFF
		SNE  V4, 0x18
		ADD  V4, 0xFF
		RET  
FUNC9:
		LD   VB, 0x00
		SNE  V4, 0x00
		JP   LABEL16
		SNE  V3, 0x00
		JP   LABEL16
		SNE  V3, 0x3F
		JP   LABEL16
		SNE  V4, 0x1F
LABEL16:
		LD   VB, 0xBB
		LD   VF, 0x00
		RET  
FUNC10:
		LD   V3, 0x08
		LD   V4, 0x08
		LD   I, DATA5
		LD   [I], BCD[VE]
		LD   V0 - V2, [I]
		CALL FUNC11
		LD   V3, 0x28
		LD   I, DATA5
		LD   [I], BCD[V6]
		LD   V0 - V2, [I]
		CALL FUNC12
		RET  
FUNC11:
		LD   I, &CHR[V0]
		DRW  V3, V4, 5
		ADD  V3, 0x06
FUNC12:
		LD   I, &CHR[V1]
		DRW  V3, V4, 5
		ADD  V3, 0x06
		LD   I, &CHR[V2]
		DRW  V3, V4, 5
		RET  
		.DB  0x01  ; .
DATA6:
		.DB  0x10 0x54 0x7C 0x6C 0x7C 0x7C 0x44 0x7C 0x7C 0x6C 0x7C 0x54 0x10 0x00 0xFC 0x78 0x6E 0x78 0xFC 0x00 0x3F 0x1E 0x76 0x1E 0x3F 0x00  ; .T|l||D||l|T...xnx..?.v.?.
DATA7:
		.DB  0x80  ; .
DATA8:
		.DB  0xA8 0x70 0xF8 0x70 0xA8  ; .p.p.
DATA9:
		.DB  0x0B 0x1B 0x28 0x38 0x30 0x20 0x10 0x00  ; ..(80 ..
DATA10:
		.DB  0x00 0x00 0x00 0x08 0x1B 0x1B 0x1B 0x18 0x04  ; .........
