; Disasembly of UFO
; Generated by chidisas8
;

	.ORG 0x200

		LD   I, DATA0
		LD   V9, 0x38
		LD   VA, 0x08
		DRW  V9, VA, 3
		LD   I, DATA1
		LD   VB, 0x00
		LD   VC, 0x03
		DRW  VB, VC, 3
		LD   I, DATA3
		LD   V4, 0x1D
		LD   V5, 0x1F
		DRW  V4, V5, 1
		LD   V7, 0x00
		LD   V8, 0x0F
		CALL FUNC0
LABEL0:
		CALL FUNC1
		SNE  V8, 0x00
LABEL1:
		JP   LABEL1
		LD   V4, 0x1E
		LD   V5, 0x1C
		LD   I, DATA2
		DRW  V4, V5, 3
		LD   VE, 0x00
LABEL2:
		LD   V6, 0x80
		LD   VD, 0x04
		SKNP VD
		LD   V6, 0xFF
		LD   VD, 0x05
		SKNP VD
		LD   V6, 0x00
		LD   VD, 0x06
		SKNP VD
		LD   V6, 0x01
		SE   V6, 0x80
		CALL FUNC3
LABEL3:
		LD   I, DATA1
		DRW  VB, VC, 3
		RND  VD, 0x01
		ADD  VB, VD
		DRW  VB, VC, 3
		SE   VF, 0x00
		JP   LABEL6
		LD   I, DATA0
		DRW  V9, VA, 3
		RND  VD, 0x01
		SE   VD, 0x00
		LD   VD, 0xFF
		ADD  V9, 0xFE
		DRW  V9, VA, 3
		SE   VF, 0x00
		JP   LABEL5
		SNE  VE, 0x00
		JP   LABEL2
		LD   I, DATA2
		DRW  V4, V5, 3
		SNE  V5, 0x00
		JP   LABEL4
		ADD  V5, 0xFF
		ADD  V4, V6
		DRW  V4, V5, 3
		SE   VF, 0x01
		JP   LABEL3
		LD   VD, 0x08
		AND  VD, V5
		SNE  VD, 0x08
		JP   LABEL5
		JP   LABEL6
LABEL4:
		CALL FUNC1
		ADD  V8, 0xFF
		JP   LABEL0
LABEL5:
		CALL FUNC0
		ADD  V7, 0x05
		JP   LABEL7
LABEL6:
		CALL FUNC0
		ADD  V7, 0x0F
LABEL7:
		CALL FUNC0
		LD   VD, 0x03
		LD   ST, VD
		LD   I, DATA2
		DRW  V4, V5, 3
		JP   LABEL4
FUNC0:
		LD   I, DATA4
		LD   [I], BCD[V7]
		LD   V3, 0x00
		CALL FUNC2
		RET  
FUNC1:
		LD   I, DATA4
		LD   [I], BCD[V8]
		LD   V3, 0x32
		CALL FUNC2
		RET  
FUNC2:
		LD   VD, 0x1B
		LD   V0 - V2, [I]
		LD   I, &CHR[V0]
		DRW  V3, VD, 5
		ADD  V3, 0x05
		LD   I, &CHR[V1]
		DRW  V3, VD, 5
		ADD  V3, 0x05
		LD   I, &CHR[V2]
		DRW  V3, VD, 5
		RET  
		.DB  0x01  ; .
DATA0:
		.DB  0x7C 0xFE 0x7C  ; |.|
DATA1:
		.DB  0x60 0xF0 0x60  ; `.`
DATA2:
		.DB  0x40 0xE0 0xA0  ; @..
DATA3:
		.DB  0xF8 0xD4  ; ..
FUNC3:
		LD   VE, 0x01
		LD   VD, 0x10
		LD   ST, VD
		RET  
