; Disasembly of VBRIX
; Generated by chidisas8
;

	.ORG 0x200

		CLS  
		CALL FUNC9
LABEL0:
		LD   V0, 0x07
		SKP  V0
		JP   LABEL0
LABEL1:
		LD   V8, 0x00
		LD   V7, 0x03
		CALL FUNC5
		CALL FUNC0
		CALL FUNC3
		CALL FUNC6
		CALL FUNC7
		CALL FUNC8
		LD   V0, K
LABEL2:
		CALL FUNC1
		CALL FUNC1
		CALL FUNC4
		CALL FUNC2
		SE   VA, 0x00
		JP   LABEL2
		LD   VC, 0x01
		CALL FUNC8
		ADD  V7, 0xFF
		CALL FUNC8
		LD   V0, 0x78
		LD   DT, V0
LABEL3:
		LD   V0, DT
		SE   V0, 0x00
		JP   LABEL3
		SE   V7, 0x00
		JP   LABEL2
		CALL FUNC8
		LD   V0, 0x07
LABEL4:
		SKP  V0
		JP   LABEL4
		JP   LABEL1
		.DB  0x00 0xFD  ; ..
FUNC0:
		LD   V9, 0x10
		LD   V0, 0x02
		LD   I, DATA0
		DRW  V0, V9, 5
		RET  
DATA0:
		.DB  0x80 0x80 0x80 0x80 0x80 0x00  ; ......
FUNC1:
		LD   V0, 0x01
		SKNP V0
		JP   LABEL5
		LD   V0, 0x04
		SKNP V0
		JP   LABEL6
		RET  
LABEL5:
		LD   V0, V9
		ADD  V0, 0xFF
		SNE  V0, 0x00
		RET  
		JP   LABEL7
LABEL6:
		LD   V0, V9
		ADD  V0, 0x01
		SNE  V0, 0x1B
		RET  
		JP   LABEL7
LABEL7:
		LD   V1, 0x02
		LD   I, DATA0
		DRW  V1, V9, 5
		DRW  V1, V0, 5
		LD   V9, V0
		RET  
FUNC2:
		LD   V0, VA
		ADD  V0, 0xFE
		SE   V0, 0x00
		RET  
		LD   V0, VB
		SUB  V0, V9
		SNE  VF, 0x00
		RET  
		LD   V1, V0
		LD   V2, 0x05
		SUB  V1, V2
		SE   VF, 0x00
		RET  
		LD   I, DATA1
		ADD  I, V0
		LD   V0 - V0, [I]
		LD   VD, V0
		SNE  VB, 0x01
		LD   VD, 0x01
		SNE  VB, 0x1E
		LD   VD, 0xFF
		LD   VC, 0x01
		LD   V0, 0x0A
		LD   ST, V0
		RET  
DATA1:
		.DB  0xFF 0xFF 0x00 0x01 0x01 0x00  ; ......
FUNC3:
		RND  VB, 0x20
		ADD  VB, 0x01
		LD   VA, 0x04
		LD   VC, 0x01
		LD   VD, 0x01
		LD   I, DATA2
		DRW  VA, VB, 1
		RET  
FUNC4:
		LD   V0, VA
		LD   V1, VB
		ADD  VA, VC
		ADD  VB, VD
		LD   I, DATA2
		SNE  VB, 0x01
		LD   VD, 0x01
		SNE  VB, 0x1E
		LD   VD, 0xFF
		SNE  VA, 0x3E
		LD   VC, 0xFF
		SNE  VA, 0x00
		LD   VC, 0x01
		DRW  V0, V1, 1
		DRW  VA, VB, 1
		SNE  VF, 0x00
		RET  
		LD   V0, VA
		LD   V1, 0x21
		SUB  V0, V1
		SNE  VF, 0x00
		RET  
		LD   V0, VA
		LD   V1, VB
		ADD  V0, 0xDE
		ADD  V1, 0xFF
		LD   V2, 0xFF
		LD   V3, 0xFF
		LD   V4, 0x03
LABEL8:
		ADD  V2, 0x01
		SUB  V0, V4
		SE   VF, 0x00
		JP   LABEL8
LABEL9:
		ADD  V3, 0x01
		SUB  V1, V4
		SE   VF, 0x00
		JP   LABEL9
		LD   V0, V2
		LD   V1, V3
		ADD  V0, V2
		ADD  V0, V2
		ADD  V1, V3
		ADD  V1, V3
		ADD  V0, 0x22
		ADD  V1, 0x01
		LD   I, DATA3
		DRW  V0, V1, 3
		ADD  VE, 0xFF
		LD   V0, 0x00
		SUBN VC, V0
		LD   V0, 0x02
		LD   ST, V0
		CALL FUNC7
		ADD  V8, 0x01
		CALL FUNC7
		SE   VE, 0x00
		RET  
		CALL FUNC6
		RET  
FUNC5:
		CLS  
		LD   V0, 0x00
		LD   V1, 0x00
		LD   V2, 0x1F
		LD   I, DATA2
LABEL10:
		DRW  V0, V1, 1
		DRW  V0, V2, 1
		ADD  V0, 0x01
		SE   V0, 0x3F
		JP   LABEL10
LABEL11:
		DRW  V0, V1, 1
		ADD  V1, 0x01
		SE   V1, 0x20
		JP   LABEL11
		RET  
DATA2:
		.DB  0x80 0x00  ; ..
FUNC6:
		LD   V1, 0x01
		LD   V3, 0x0A
		LD   I, DATA3
LABEL12:
		LD   V0, 0x22
		LD   V2, 0x07
LABEL13:
		DRW  V0, V1, 3
		ADD  V0, 0x03
		ADD  V2, 0xFF
		SE   V2, 0x00
		JP   LABEL13
		ADD  V1, 0x03
		ADD  V3, 0xFF
		SE   V3, 0x00
		JP   LABEL12
		LD   VE, 0x46
		RET  
DATA3:
		.DB  0xE0 0xA0 0xE0 0x00  ; ....
FUNC7:
		LD   I, DATA4
		LD   [I], BCD[V8]
		LD   V0 - V2, [I]
		LD   V3, 0x03
		LD   V4, 0x02
		LD   I, &CHR[V0]
		DRW  V3, V4, 5
		ADD  V3, 0x05
		LD   I, &CHR[V1]
		DRW  V3, V4, 5
		ADD  V3, 0x05
		LD   I, &CHR[V2]
		DRW  V3, V4, 5
		RET  
DATA4:
		.DB  0x00 0x00 0x00 0x00 0x00 0x00  ; ......
FUNC8:
		LD   V0, 0x14
		LD   V1, 0x02
		LD   I, &CHR[V7]
		DRW  V0, V1, 5
		RET  
FUNC9:
		LD   V0, 0x0A
		LD   V1, 0x0C
		LD   V2, 0x09
		LD   V3, 0x05
		LD   I, DATA5
LABEL14:
		DRW  V0, V1, 5
		ADD  I, V3
		ADD  V0, 0x05
		ADD  V2, 0xFF
		SE   V2, 0x00
		JP   LABEL14
		RET  
DATA5:
		.DB  0x90 0x90 0x90 0x90 0x60 0xE0 0x90 0xE0 0x90 0xE0 0xE0 0x90 0xE0 0x90 0x90 0x20 0x20 0x20 0x20 0x20 0x90 0x90 0x60 0x90 0x90 0x00 0x00 0x60 0x00 0x00 0xF0 0x90 0xF0 0x80 0x80 0xF0 0x80 0xF0 0x10 0xF0 0xE0 0x90 0xE0 0x90 0x90  ; ....`..........     ..`....`.................
