; Disasembly of WIPEOFF
; Generated by chidisas8
;

	.ORG 0x200

		LD   I, DATA1
		LD   VA, 0x07
		LD   V1, 0x00
LABEL0:
		LD   VB, 0x08
		LD   V0, 0x00
LABEL1:
		DRW  V0, V1, 1
		ADD  V0, 0x08
		ADD  VB, 0xFF
		SE   VB, 0x00
		JP   LABEL1
		ADD  V1, 0x04
		ADD  VA, 0xFF
		SE   VA, 0x00
		JP   LABEL0
		LD   V6, 0x00
		LD   V7, 0x10
		LD   I, DATA2
		LD   V0, 0x20
		LD   V1, 0x1E
		DRW  V0, V1, 1
LABEL2:
		LD   V3, 0x1D
		LD   V2, 0x3F
		AND  V2, V0
		ADD  V7, 0xFF
		SNE  V7, 0x00
		JP   LABEL7
		LD   VF, K
LABEL3:
		LD   I, DATA0
		DRW  V2, V3, 1
		LD   V5, 0xFF
		RND  V4, 0x01
		SE   V4, 0x01
		LD   V4, 0xFF
LABEL4:
		LD   I, DATA2
		LD   VC, 0x00
		LD   VE, 0x04
		SKNP VE
		LD   VC, 0xFF
		LD   VE, 0x06
		SKNP VE
		LD   VC, 0x01
		DRW  V0, V1, 1
		ADD  V0, VC
		DRW  V0, V1, 1
		SNE  VF, 0x01
		JP   LABEL5
		SNE  V2, 0x00
		LD   V4, 0x01
		SNE  V2, 0x3F
		LD   V4, 0xFF
		SNE  V3, 0x00
		LD   V5, 0x01
		SNE  V3, 0x1F
		JP   LABEL6
		LD   I, DATA0
		DRW  V2, V3, 1
		ADD  V2, V4
		ADD  V3, V5
		DRW  V2, V3, 1
		SE   VF, 0x01
		JP   LABEL4
		SNE  V3, 0x1E
		JP   LABEL5
		LD   VA, 0x02
		LD   ST, VA
		ADD  V6, 0x01
		SNE  V6, 0x70
		JP   LABEL7
		DRW  V2, V3, 1
		RND  V4, 0x01
		SE   V4, 0x01
		LD   V4, 0xFF
		RND  V5, 0x01
		SE   V5, 0x01
		LD   V5, 0xFF
		JP   LABEL4
LABEL5:
		LD   VA, 0x03
		LD   ST, VA
		LD   I, DATA0
		DRW  V2, V3, 1
		ADD  V3, 0xFF
		JP   LABEL3
LABEL6:
		LD   I, DATA0
		DRW  V2, V3, 1
		JP   LABEL2
LABEL7:
		LD   I, DATA2
		DRW  V0, V1, 1
		LD   I, DATA3
		LD   [I], BCD[V6]
		LD   V0 - V2, [I]
		LD   V3, 0x18
		LD   V4, 0x1B
		LD   I, &CHR[V0]
		DRW  V3, V4, 5
		ADD  V3, 0x05
		LD   I, &CHR[V1]
		DRW  V3, V4, 5
		ADD  V3, 0x05
		LD   I, &CHR[V2]
		DRW  V3, V4, 5
LABEL8:
		JP   LABEL8
		.DB  0x01  ; .
DATA0:
		.DB  0x80  ; .
DATA1:
		.DB  0x44  ; D
DATA2:
		.DB  0xFF  ; .
